#### The config file for lifelong class incremental learning with FGN.
#### For cora pubmed and citeseer we use the featBrd layer
dataset=cora # pubmed
model=attnplain
device=cuda:0
seed=1

sample=10
jump=1
memory=512
batch=6
opt=SGD
lr=0.01
iteration=5

hidden =[10, 10]
drop = [0.3, 0.1]